# Generated by Django 2.2.4 on 2019-09-01 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('FileName', models.CharField(blank=True, max_length=256, null=True)),
                ('Url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField()),
                ('Name', models.CharField(max_length=40)),
                ('Number', models.IntegerField()),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('PictureID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Relationship_Picture', to='HelloWorld.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Account', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Status', models.IntegerField()),
                ('Gender', models.IntegerField()),
                ('Email', models.CharField(max_length=30)),
                ('LastLoginIP', models.IntegerField()),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('PictureID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_Picture', to='HelloWorld.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship_Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User1_Relationship_User2', models.CharField(max_length=40)),
                ('User2_Relationship_USer1', models.CharField(max_length=40)),
                ('User1_Name_User2', models.CharField(max_length=40)),
                ('User2_Name_User2', models.CharField(max_length=40)),
                ('User1_Check', models.IntegerField()),
                ('User2_Check', models.IntegerField()),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('RelationshipID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Personal_Relationship', to='HelloWorld.Relationship')),
                ('User1ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User1', to='HelloWorld.User')),
                ('user2ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User2', to='HelloWorld.User')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('RelationshipID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Group_Relationship', to='HelloWorld.Relationship')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Group_User', to='HelloWorld.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField()),
                ('Content', models.TextField()),
                ('Status', models.IntegerField()),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('ChatRoomID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Message_ChatRoom', to='HelloWorld.ChatRoom')),
                ('SenderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sender', to='HelloWorld.User')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='PictureID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ChatRoom_Picture', to='HelloWorld.Picture'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='RelationshipID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ChatRoom_Relationship', to='HelloWorld.Relationship'),
        ),
    ]
